birth_fn = "emevo.birth_and_death.SlopeELBirth"
hazard_fn = "emevo.birth_and_death.SlopeELGHazard"

[hazard_params]
scale = 0.01
alpha = 0.1
slope = 1.0 # 0.2
alpha_age = 1e-6
beta = 1e-5

[birth_params]
scale = 4e-4
slope = 0.1