birth_fn = "emevo.birth_and_death.SlopeELBirth"
hazard_fn = "emevo.birth_and_death.SlopeELGHazard"

[hazard_params]
scale = 0.01
alpha = 0.02
slope = 0.2
alpha_age = 2e-7
beta = 4e-6

[birth_params]
scale = 1e-3
slope = 0.1
const = -5e-4