birth_fn = "emevo.birth_and_death.SlopeELBirth"
hazard_fn = "emevo.birth_and_death.SlopeELGHazard"

[hazard_params]
scale = 0.01
alpha = 0.02
slope = 0.2
alpha_age = 4e-7
beta = 1e-6

[birth_params]
scale = 1e-3
slope = 0.4
delay = 10.0
const = 0.0