birth_fn = "emevo.birth_and_death.HeavisideBirth"
hazard_fn = "emevo.birth_and_death.SlopeELGHazard"

[hazard_params]
scale = 0.01
alpha = 0.02
slope = 0.2
alpha_age = 4e-7
beta = 2e-6

[birth_params]
threshold = 20.0