#!/bin/bash
set -eo pipefail

if [[ -d .exp-venv ]]; then
    exit 0
fi

mkdir .exp-venv
python -m venv .exp-venv
if [[ -f requirements/experiments.txt ]]; then
    nox -s compile -- -k experiments
fi
source .venv/bin/activate
pip install pip-tools
pip-sync requirements/experiments.txt
