#!/bin/bash
set -eo pipefail

if [[ ! -d .exp-venv ]]; then
    mkdir .exp-venv
    python -m venv .exp-venv
fi

if [[ ! -f requirements/experiments.txt ]]; then
    nox -s compile -- -k experiments
fi

source .exp-venv/bin/activate
pip install pip-tools
pip-sync requirements/experiments.txt
