n_initial_agents = 20
n_max_agents = 100
n_max_foods = 20
food_num_fn = ["logistic", 0.01, 20]
food_loc_fn = "gaussian"
agent_loc_fn = "uniform"
xlim = [0.0, 360.0]
ylim = [0.0, 240.0]
env_radius = 120.0
env_shape = "square"
neighbor_stddev = 40.0
n_agent_sensors = 16
sensor_length = 100.0
sensor_range = "wide"
agent_radius = 10.0
food_radius = 4.0
foodloc_interval = 1000
dt = 0.1
linear_damping = 0.8
angular_damping = 0.6
max_force = 40.0
min_force = -20.0
init_energy = 20.0
energy_capacity = 100.0
force_energy_consumption = 0.01 / 40.0
energy_share_ratio = 0.4
n_velocity_iter = 6
n_position_iter = 2
n_physics_iter = 5
max_place_attempts = 10
