n_initial_agents = 50
n_max_agents = 150
n_max_foods = 80
n_food_sources = 2
food_num_fn = [
    ["logistic", 15, 0.01, 30],
    ["logistic", 15, 0.01, 30],
]
food_loc_fn = [
   ["gaussian", [360.0, 270.0], [48.0, 36.0]],
   ["gaussian", [120.0, 90.0], [48.0, 36.0]],
]
agent_loc_fn = "uniform"
xlim = [0.0, 480.0]
ylim = [0.0, 360.0]
env_shape = "square"
neighbor_stddev = 100.0
n_agent_sensors = 16
sensor_length = 120.0
sensor_range = "wide"
agent_radius = 10.0
food_radius = 4.0
foodloc_interval = 1000
dt = 0.1
linear_damping = 0.8
angular_damping = 0.6
max_force = 80.0
min_force = -20.0
init_energy = 40.0
energy_capacity = 120.0
force_energy_consumption = 2e-5
energy_share_ratio = 0.4
n_velocity_iter = 6
n_position_iter = 2
n_physics_iter = 5
max_place_attempts = 10