n_initial_agents = 100
n_max_agents = 200
n_max_foods = 120
food_num_fn = ["linear", 40, 0.2, 120]
food_loc_fn = "uniform"
agent_loc_fn = "uniform"
xlim = [0.0, 540.0]
ylim = [0.0, 540.0]
env_shape = "square"
neighbor_stddev = 100.0
n_agent_sensors = 24
sensor_length = 200.0
sensor_range = "wide"
agent_radius = 10.0
food_radius = 4.0
foodloc_interval = 1000
dt = 0.1
linear_damping = 0.8
angular_damping = 0.6
max_force = 80.0
min_force = -20.0
init_energy = 80.0
energy_capacity = 400.0
force_energy_consumption = 1e-5
basic_energy_consumption = 5e-4
energy_share_ratio = 0.4
n_velocity_iter = 6
n_position_iter = 2
n_physics_iter = 5
max_place_attempts = 10
n_max_food_regen = 10
n_max_predators = 40
predator_radius = 14.0
predator_sensor_length = 200
predator_init_energy = 20.0
predator_force_ec = 0.0001
predator_basic_ec = 0.0
