n_initial_agents = 20
n_max_agents = 120
n_max_foods = 50
food_num_fn = ["logistic", 20, 0.01, 50]
food_loc_fn = [
   "switching",
   100,
   ["gaussian", [240, 80], [40, 40]],
   ["gaussian", [240, 400], [40, 40]]
]
agent_loc_fn = "uniform"
xlim = [0.0, 480.0]
ylim = [0.0, 480.0]
env_shape = "circle"
env_radius = 240
neighbor_stddev = 100.0
n_agent_sensors = 16
sensor_length = 120.0
sensor_range = "wide"
agent_radius = 10.0
food_radius = 4.0
foodloc_interval = 1000
dt = 0.1
linear_damping = 0.8
angular_damping = 0.6
max_force = 40.0
min_force = -20.0
init_energy = 40.0
energy_capacity = 120.0
force_energy_consumption = 4e-5
energy_share_ratio = 0.4
n_velocity_iter = 6
n_position_iter = 2
n_physics_iter = 5
max_place_attempts = 10