path = "emevo.genetic_ops.BernoulliMixtureMutation"

[params]
mutation_prob = 0.1

[params.mutator]
path = "emevo.genetic_ops.UniformMutation"

[params.mutator.params]
min_noise = -1.0
max_noise = 1.0
