name: Tests
on:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '*.md'
jobs:
  tests:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - {name: Linux, python: '3.10', os: ubuntu-latest, nox: "tests"}
          - {name: Windows, python: '3.10', os: windows-latest, nox: "tests"}
          - {name: Mac, python: '3.10', os: macos-latest, nox: "tests"}
          - {name: Py39, python: '3.9', os: ubuntu-latest, nox: "tests"}
          - {name: Py38, python: '3.8', os: ubuntu-latest, nox: "tests"}
          - {name: Lint, python: '3.10', os: ubuntu-latest, nox: "lint"}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - run: pip install nox
      - run: nox --session=${{ matrix.nox }} --python=${{ matrix.python }}
